apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: cert-manager
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/AloisReitbauer/progressiveDelivery-masterclass.git'
    targetRevision: main
    path: "gitops/manifests/cert-manager"
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true