# this image is built and updated weekly
# https://github.com/cse-labs/codespaces-images

FROM checkelmann/kind:latest

# some images require specific values
ARG USERNAME=vscode
#ENV PATH $PATH:/home/${USERNAME}/.dapr/bin